# Generated by Django 3.2.19 on 2023-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='meta_content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='meta_image',
            field=models.URLField(default=None, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='meta_title',
            field=models.TextField(default=None, null=True),
        ),
    ]
