# Generated by Django 3.2.19 on 2023-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20230531_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
