# Generated by Django 3.2.19 on 2023-06-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiseraccountservicelevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.url'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.url'),
        ),
        migrations.AlterField(
            model_name='pinnedtweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user'),
        ),
        migrations.AlterField(
            model_name='status',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.place'),
        ),
        migrations.AlterField(
            model_name='status',
            name='quoted_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted', to='twitter.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='retweet_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet', to='twitter.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.url'),
        ),
    ]
